name: Acceptance Test runner

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  kiran-d2:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'kiran-d2' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: kiran-d2 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d2.gptfu.com:6080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  joel-dev4:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'joel-dev4' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: joel-dev4 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://dev4.gptfu.com:6080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  madhu-d:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'madhu-d' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: madhu-d Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d.gptfu.com:6082" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
  anuj-d3:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'anuj-d3' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: anuj-d3 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d3.gptfu.com:9080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  madhusri-dev5:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'madhusri-dev5' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: madhusri-dev5 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://dev5.gptfu.com:6080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  phani-dev4:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'phani-dev4' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: phani-dev4 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://dev4.gptfu.com:9080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  pashu-dev5:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'pashu-dev5' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: pashu-dev5 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://dev5.gptfu.com:9081" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
  mira-d3:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'mira-d3' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: mira-d3 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d3.gptfu.com:8080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  hari-d3:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'hari-d3' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: hari-d3 Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d3.gptfu.com:7080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports

  aman-d:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'aman-d' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: aman-d Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d.gptfu.com:4080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
  varun-d:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'varun-d' }}
    steps:
        - uses: actions/checkout@v3
        - name: Create folder for reports
          run: mkdir reports
        - name: aman-d Test Suite runner
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa --variable URL:http://d.gptfu.com:9080" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
