name: dev4-6080 Test Suite runner

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run_tests1:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: checkTitle
        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Create folder for reports
        run: mkdir reports

      - name: dev4-9081 Test Suite runner
        if: startsWith(steps.checkTitle.outputs.title, 'Run1')
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests/dev4-6080:/opt/robotframework/tests/dev4-6080:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports

  run_tests2:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: checkTitle
        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Create folder for reports
        run: mkdir reports

      - name: dev4-9081 Test Suite runner
        if: startsWith(steps.checkTitle.outputs.title, 'Run2')
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests/dev4-9081:/opt/robotframework/tests/dev4-9081:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports

  run_tests3:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: checkTitle
        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Create folder for reports
        run: mkdir reports

      - name: dev4-9081 Test Suite runner
        if: startsWith(steps.checkTitle.outputs.title, 'Run3')
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests/dev5:/opt/robotframework/tests/dev5:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
