name: dev4-6080 Test Suite runner

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run_tests1:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        id: checkTitle
        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Create folder for reports
        run: mkdir reports

      - name: dev4-6080 Test Suite runner
        run: |
          title="${{ steps.checkTitle.outputs.title }}"
          if [[ $title == *Run Tests 1* ]]; then
            # Add your command for running Tests 1 here
          fi

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
