name: dev4-6080 Test Suite runner

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 1 1 *'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from the repository
        uses: actions/checkout@v3

      - name: Create folder for reports
        run: mkdir reports

      - name: Trigger test suite run
        id: trigger_tests
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'YOUR_WORKFLOW_ID',  // Replace with the actual workflow ID
              ref: context.sha
            });
            console.log(response);

      - name: Wait for user input
        if: always()
        uses: andstor/actions-wait-for-input@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {"prompt": "Start the test suite run?", "required": true}

      - name: Run Robot Framework tests inside a Docker container
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests/dev4-6080:/opt/robotframework/tests/dev4-6080:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest

      - name: Upload reports as a zip file
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ${{ github.workspace }}/reports
