name: Test Every 2 Minutes

on:
  schedule:
    - cron: "*/3 * * * *"   # This schedule runs every 2 minutes

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for reports
        run: mkdir reports
      - name: Run Robot Framework Tests
        run: |
          docker run \
            -v ${PWD}/reports:/opt/robotframework/reports:Z \
            -v ${PWD}/tests:/opt/robotframework/tests:Z \
            -e ROBOT_OPTIONS="--variable DINOSAUR:${{ github.event.inputs.DINOSAUR }} --variable NOT_DINOSAUR:${{ github.event.inputs.NOT_DINOSAUR }} --include ${{ github.event.inputs.tag }}" \
            --user $(id -u):$(id -g) \
            ppodgorsek/robot-framework:latest
      - name: Upload reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image privileges.
          path: ${{ github.workspace }}/reports
      - name: Wait for 2 minutes
        run: sleep 120
