name: Run Robot Framework Tests
on:
  pull_request:
    branches:
      - master

jobs:
  choose_action:
    runs-on: ubuntu-latest
    steps:
      - name: Request Action Input
        id: choose_action
        run: |
          echo "::set-output name=selected_action::$(echo -e 'Action 1\nAction 2' | fzf)"

  run_action:
    needs: choose_action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create folder for reports
        run: mkdir reports

      - name: Run Selected Action
        run: |
          selected_action="${{ needs.choose_action.outputs.selected_action }}"
          case $selected_action in
            "Action 1")
              docker run \
                -v ${PWD}/reports:/opt/robotframework/reports:Z \
                -v ${PWD}/tests:/opt/robotframework/tests:Z \
                -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
                --user $(id -u):$(id -g) \
                ppodgorsek/robot-framework:latest
              ;;
            "Action 2")
              docker run \
                -v ${PWD}/reports:/opt/robotframework/reports:Z \
                -v ${PWD}/tests2:/opt/robotframework/tests2:Z \
                -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
                --user $(id -u):$(id -g) \
                ppodgorsek/robot-framework:latest
              ;;
            *)
              echo "Invalid action selected"
              exit 1
              ;;
          )

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports
