name: Tests on gptfu

on:
  push:
    # runs tests for commits pushed to master
    branches:
      - master
    # do not run tests if file README.md changes
    paths-ignore:
      - '**.md'
    # run tests for GitHub Pull requests. Test result is visible in the Pull Request page.
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
    s2_runner:
        runs-on: ubuntu-latest
        steps:
        # checkout code from a repository
        - uses: actions/checkout@v3
        # create folder for test reports
        - name: Create folder for reports
          run: mkdir reports
        # run Robot Framework tests inside Docker container
        - name: Run Robot Framework Tests
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests/gptfu-tests:/opt/robotframework/tests/gptfu-tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
            path: ${{ github.workspace }}/reports
